name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/Carneiro.Terramotos.sln
    - name: Install Dependencies
      run: cd ./src/Carneiro.Terramotos.Web
      run: npm Install
      run: cd .. ; cd .. ;
    - name: Build
      run: dotnet build --no-restore ./src/Carneiro.Terramotos.sln
